export const SHOPPING = {
  SETSTORE: "SHOPPING_SETSTORE",
  INCREMENT: "SHOPPING_INCREMENT",
  DECREMENT: "SHOPPING_DECREMENT",
  COUNT_CART_ITEMS: "COUNT_CART_ITEMS"
};

export const FORMFIELD = {
  VALIDATION: {
    REQUIRED: "FIELD_REQUIRED",
    EMAIL: "FIELD_EMAIL",
    TOUCHED: "FIELD_TOUCHED"
  },
  CREATE: "FORM_CREATE"
}
